### ISSUE TITLE
Program skips a line after "read"

### ISSUE THREAD

**Issue by AliengirlLiv** [shickey/HMMM.js#2]
My program will skip a line after a "read" line when you press "Run" in the simulator.  When you step through the program, it works correctly.

**Comment by shickey** [comment]
Can you provide the HMMM code that is causing this issue?

**Comment by bwiedermann** [comment]
I also see this issue. I ran the following program in Firefox 41.0 on a Mac:

```
0 setn r1 100
1 read r1
2 write r1
3 halt
```

When I click the `Run` button and enter the input `42`, the program reads the input (i.e., the value of r1 is 42), but prints 100 (the initial value of the register, _before_ the read). I've included a screenshot below. When I step through the program, it does the correct thing (i.e., it prints 42). I only see this issue in Firefox, I don't see it in Chrome (45.0 on a Mac) or Safari (version 8.0.8 on a Mac). Perhaps there's some kind of race condition that shows up only in Firefox?

(By the way, thank you for making this simulator. We're using it class at Harvey Mudd this semester, and it's much better than how we were doing it before.)

<img width="1258" alt="screen shot 2015-09-25 at 8 45 11 am" src="https://cloud.githubusercontent.com/assets/2831333/10105093/d15bf0a4-6361-11e5-9e84-adcfd790221d.png">

**Comment by shickey** [comment]
Fascinating! Indeed I can replicate this in Firefox 41 and it appears that if I repeatedly hit "reset" followed by "run" and enter 42, it sometimes prints 42 and sometimes prints 100. Definitely seems like a race condition. I'll try to look into it soon. Also, feel free to fork the repo and submit a pull request if you find a solution before I do.

Glad to hear you all are enjoying it at Harvey Mudd! Let me know if you have any one who would be interested in developing it further. I have some ideas for where to go next with it.

**Comment by bwiedermann** [comment]
I tried changing the code that runs a program, [from a callback to a while loop](https://github.com/bwiedermann/HMMM.js/commit/2e599fb76f1aca472e4d6767dec3d14147efc809). I tested it once in Firefox and it seemed to work :). I'm not sure how this change might affect the rest of the code, though. Do you think this will work?

**Comment by shickey** [comment]
Cool. Yeah, I figured it had something to do with that callback structure (which was a bit of a hack to begin with, if I recall correctly). A while loop will certainly work, in the sense that it will (probably) remove that race condition. However, one thing I want to keep in the structure of the simulator is the notion of a specific time delay between each instruction execution. Two reasons for this: first is that this will hopefully make the simulator run similarly on different machines (i.e., a while loop will let the JS engine process instructions as fast as possible so I imagine on newer machines the instructions will run faster and thus it'll be harder to see what the simulator is actually doing (though this is speculative)). Moreover, I would eventually like to be able to add an "execution speed" slider into the UI so that students can speed up the simulation when they want it to go fast and slow down the simulation when they want to see what exactly is happening at each step or are debugging.

I think the ultimate solution to this problem is to move away from using `prompt()` as the user input method and instead build an input text box into the UI itself. Or better yet, when a `read` instruction happens, allow the user to enter their input directly through the existing console UI (though I imagine that will be a more significant undertaking).

**Comment by shickey** [comment]
Fixed in 28033d7. Turned out setting the timeout to run the next instruction was called before running the current instruction which sometimes caused a race condition in Firefox.
